# Mod Attributes
    mod_version = 1.0.3
    mod_id = critterfights
    maven_group = dev.itsmeow.critterfights
    at_file = accesstransformer

# Forge
    mc_version = 1.21.1
    neo_version = 21.1.73
    mappings_mc_version = 1.21
    mappings_version = 2024.07.28

# Publishing
    github = itsmeow/CritterFights
    name = Critter Fights
    url = https://github.com/itsmeow/CritterFights
    curse_project_id = 351798
    curse_title = Critter Fights
    curse_versions = Java 21,NeoForge,Minecraft 1.21:1.21.1

# Misc
    org.gradle.jvmargs=-Xmx6G
    org.gradle.daemon=true
    forgegradle_version=1.0.21
    java_version=21
